### ISSUE TITLE
Improve items listed by Lighthouse report

### ISSUE THREAD

**Issue by codemicro** [riceteacatpanda/homepage#23]
Checklist of items to fix from the latest two Lighthouse reports ([1](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://riceteacatpanda.wtf)) ([2](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https://riceteacatpanda.wtf/whoarewe/))

**Generic**
- ~~Browser errors were logged to the console~~
  - ~~Fixed, caused by a syntax error in GA code~~
- ~~Nothing has meta descriptions (Added in #26)~~
- Tap targets are not sized appropriately (mobile)
  - "Interactive elements like buttons and links should be large enough (48x48px), and have enough space around them, to be easy enough to tap without overlapping onto other elements. [Learn more.](https://web.dev/tap-targets)"

**About us**
- ~~Image elements do not have [alt] attributes (Remedied in #27)~~
  - ~~Specifically images in Vihan's and Cake's bios~~
- Images are displayed with an incorrect ratio
  - Speficially Cake's profile picture - because it's only a generic one, it's slightly different to the rest.

|                                                                            	| URL                                  	| Aspect Ratio (Displayed) 	| Aspect Ratio (Actual) 	|
|----------------------------------------------------------------------------	|--------------------------------------	|--------------------------	|-----------------------	|
| ![img](https://discordapp.com/assets/322c936a8c8be1b803cd94861bdfa868.png) 	| /assets/322c936….png(discordapp.com) 	| 128 x 256 (0.50)         	| 256 x 256 (1.00)      	|

**Comment by vihanb** [comment]
Assets we can pre-optimize (progressive loading, etc.) during the build process— it's a bit complex but I think it's possible to do nicely with eleventy.

**Comment by vihanb** [comment]
Optimally we'd also modularize+optimize CSS per page but not sure if that's reasonably possible with a framework like eleventy.
